// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTmRPVBVaZu8B0tb74z98fccTlqcIR-bA',
    appId: '1:1024091971826:web:b75749d3ef14b3ff94706b',
    messagingSenderId: '1024091971826',
    projectId: 'gaza-secret',
    authDomain: 'gaza-secret.firebaseapp.com',
    storageBucket: 'gaza-secret.appspot.com',
    measurementId: 'G-8KKMXZ927J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiNZXEV3orcys05clcrGNgCR7IE5E1aX8',
    appId: '1:1024091971826:android:d6103cffe6baba6294706b',
    messagingSenderId: '1024091971826',
    projectId: 'gaza-secret',
    storageBucket: 'gaza-secret.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCapNZZ-HLCfqmnlfaTqsHPqVd-q_YOfjQ',
    appId: '1:1024091971826:ios:a2199417e742adbe94706b',
    messagingSenderId: '1024091971826',
    projectId: 'gaza-secret',
    storageBucket: 'gaza-secret.appspot.com',
    iosBundleId: 'com.example.gazaSecret',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCapNZZ-HLCfqmnlfaTqsHPqVd-q_YOfjQ',
    appId: '1:1024091971826:ios:5dab3c93ee3678fa94706b',
    messagingSenderId: '1024091971826',
    projectId: 'gaza-secret',
    storageBucket: 'gaza-secret.appspot.com',
    iosBundleId: 'com.example.gazaSecret.RunnerTests',
  );
}
